### ISSUE TITLE
ASM as file assets instead of strings

### ISSUE THREAD

**Issue by robin-raymond** [sehugg/dithertron#16]
I think it would be worth making the assembly code text asm asset text files that are imported as strings at compile time rather than putting them into the export as strings. Maybe using something like raw-loader? I don't want to mess with your project files but I think that would be a nice cleanup.

**Comment by sehugg** [comment]
Yes, definitely. It's gotten a little unwieldy. It needs to be refactored into TS modules, but splitting up files is a first good step. It uses esbuild so the typical webpack stuff isn't available, but maybe plain old fetch() might work.
