### ISSUE TITLE
Zx spectrum dark mode

### ISSUE THREAD

**Issue by robin-raymond** [sehugg/dithertron#22]
The current Zx spectrum implementation only dithers "bright" mode colors. I think it's possible with a few tweaks to enable proper usage of the 'i' color attribute and expand the color palette as a result.

**Comment by robin-raymond** [comment]
BEFORE:
<img width="382" alt="zx-before" src="https://github.com/sehugg/dithertron/assets/2962646/d98b3b58-93dc-4501-9150-77fc00f0a8f5">

AFTER:
<img width="382" alt="zx-after" src="https://github.com/sehugg/dithertron/assets/2962646/24387164-f510-45e7-b1f2-35f65ee304a3">

**Comment by sehugg** [comment]
That's dark mode? Cool :)

**Comment by robin-raymond** [comment]
The user can now select, default (both light and dark in the same picture), a dark mode palette, a bright mode palette, a dark selection forced bright, or a bright selection forced dark.

**Comment by sehugg** [comment]
ZX looks good! The modes all have different personalities. I think ZX looks best with the Hue-Based color function. I also started on some unit tests to see if these differences can be quantified. Thanks!

**Comment by robin-raymond** [comment]
Agreed. I've been creating a good base class for both, and adding intellivision support.
