### ISSUE TITLE
MSX/Coleco (TMS9918A) preview vs workshop look entirely different

### ISSUE THREAD

**Issue by robin-raymond** [sehugg/dithertron#23]
Just making note that this routine is busted before I push my latest changes. I will try to look into this after the Zx to see what's going wrong.

<img width="826" alt="coleco1" src="https://github.com/sehugg/dithertron/assets/2962646/f9c51f35-9de4-4c94-9deb-47401584c129">

<img width="769" alt="coleco2" src="https://github.com/sehugg/dithertron/assets/2962646/a43b5a64-d27c-454a-91cd-7c91799e97b1">

**Comment by sehugg** [comment]
Hmm yeah, looks like background color.

**Comment by robin-raymond** [comment]
The fix is up. The transparency palette color is remapped to black (which is how this color is listed in the palette). There's no point in supporting the transparency color because the background color is available via the palette, so there's no way to get an extra color from using the transparency color with the background color somehow. And the routine has no reason to pick the background color via the transparency vs directly choosing the color via the palette. There's further no obvious way to use the transparency in some way that could be beneficial to a programmer in an automated way. The only thing I could think of is having an option where the programmer can choose "green" or whatever palette color and instead map that to transparency and use the extra bits to indicate the background color of "green". But let's leave this feature until someone has an ask and an explanation how they intend to use it (so it's not a wasted feature nobody would find a use for).
