### ISSUE TITLE
Online Dithertron busted

### ISSUE THREAD

**Issue by robin-raymond** [sehugg/dithertron#28]
I don't think it's related to the changes I did as I don't think they are deployed yet... at least I hope not, but it's not working right now. Black screen in the preview. Do you have a log entry somewhere that shows the deployment commit?

I see this in the logs which I've not seen before, is it related?
````log
Failed to load resource: the server responded with a status of 404 (Not Found)
https://8bitworkshop.com/dithertron/fonts/fontawesome-webfont.ttf?v=4.7.0
````

**Comment by robin-raymond** [comment]
Never mind. Nothing to see here. I was likely just attempting during a deploy ;-)

**Comment by sehugg** [comment]
I think you're right, those are missing fonts for the download buttons. I'll fix.
