### ISSUE TITLE
Update routine can cause "sync" issue between image and palette selection

### ISSUE THREAD

**Issue by robin-raymond** [sehugg/dithertron#33]
This code in the dither.update can cause issue:

````ts
        // set new pixel rgb
        const errmag = (Math.abs(err[0]) + Math.abs(err[1]*2) + Math.abs(err[2])) / (256 * 4);
        if (this.indexed[offset] != palidx && errmag >= this.errorThreshold) {
            this.indexed[offset] = palidx;
            this.changes++;
        }
````

Specifically, the code picks the "best" color from the "valid" from the canvas, but then decides if it should update the indexed to the new value based on the error threshold. That's all fine, most time. Except sometimes what is valid changes on some canvases, e.g. the cell block color gets re-chosen to a new value so a palette index which was valid is no longer value. Thus the value in `this.indexed` might have an illegal value, but the error threshold was not exceeded so it was never updated. This happens rarely but it does happen, and when it does happen the export routine has an assertion failure because the index points to a color that was never chosen nor legal (at least anymore).

Since I'm working on a fix anyway, this is what I propose: if the error threshold is not exceeded, leave the value alone EXCEPT double check the value is still legal. If it's not legal then force the value to update regardless of the error value.

FYI - The proposed fix works to address the issue for me.

**Comment by sehugg** [comment]
Hmm, good catch! I should probably add the export routines to the tests.

I wonder if this would do it:
```
        if (this.indexed[offset] != palidx && errmag >= this.errorThreshold) {
            this.changes++;
        }
        this.indexed[offset] = palidx;
```

**Comment by robin-raymond** [comment]
Yes, that would fix too. I did a fix too. You can decide which logic is best, to always pick the closest but don't consider it a change if it's not within the threshold, or only pick the closest if it's inside the threshold (or force it to pick the current value is no longer legal). I did the second approach but I don't know if that's better or worse!

**Comment by robin-raymond** [comment]
This is now fixed.
